name: OpenTofu CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  opentofu:
    name: "OpenTofu"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./tofu/web

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup OpenTofu
        uses: opentofu/setup-opentofu@v1
        
      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: OpenTofu Init
        run: |
          tofu init \
            -backend-config="bucket=${{ secrets.GCS_BUCKET }}" \
            -backend-config="prefix=web/terraform/state"

      - name: OpenTofu Validate
        run: tofu validate -no-color

      - name: OpenTofu Plan
        run: tofu plan -no-color
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_image_name: ${{ secrets.DOCKER_IMAGE_NAME }}
          TF_VAR_image_tag: ${{ github.sha }}

      - name: OpenTofu Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: tofu apply -auto-approve -no-color
        env:
          TF_VAR_project_id: ${{ secrets.GCP_PROJECT_ID }}
          TF_VAR_image_name: ${{ secrets.DOCKER_IMAGE_NAME }}
          TF_VAR_image_tag: ${{ github.sha }}
